controllers:
    resource: '../src/Controller/'
    type:     annotation

# redirecting the homepage
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /user/list
        permanent: true